server:
  port: 80
  context-path: /

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/db_blog?useSSL=false
      username: root
      password: 123456
   jpa:
     show-sql: true
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiang.entity